"""
Apify Subtitle Testi
Apify'ın altyazı çekme özelliğini test eder ve SRT'yi parse eder
"""

from apify_client import ApifyClient
from dotenv import load_dotenv
import os

def parse_srt_to_text(srt_content):
    """SRT formatını düz metne çevirir"""
    lines = srt_content.split('\n')
    text_lines = []

    for line in lines:
        line = line.strip()
        if not line or line.isdigit() or '-->' in line:
            continue
        text_lines.append(line)

    return ' '.join(text_lines)

load_dotenv()

client = ApifyClient(os.getenv('APIFY_API_KEY'))
video_url = "https://youtu.be/VtHvkBWToJs"

run_input = {
    "startUrls": [{"url": video_url}],
    "downloadSubtitles": True,
    "saveSubtitlesToKVS": True,
    "subtitleLang": "en",
    "preferAutoGeneratedSubtitles": False,
}

print("🧪 Apify actor test ediliyor...")
print(f"📺 Video: {video_url}")
print()

try:
    run = client.actor("streamers/youtube-scraper").call(run_input=run_input)

    print("✅ Actor çalıştırıldı")
    print(f"🆔 Run ID: {run.get('id')}")
    print()

    # Dataset'ten altyazıları çek
    print("📊 Dataset kontrol ediliyor...")
    for item in client.dataset(run["defaultDatasetId"]).iterate_items():
        print(f"  📹 Video: {item.get('title', 'N/A')}")

        if 'subtitles' in item and item['subtitles']:
            subtitles_list = item['subtitles']

            if isinstance(subtitles_list, list) and len(subtitles_list) > 0:
                subtitle_item = subtitles_list[0]
                print(f"  ✅ Altyazı bulundu!")
                print(f"  📝 Dil: {subtitle_item.get('language', 'N/A')}")
                print(f"  🔤 Tip: {subtitle_item.get('type', 'N/A')}")

                if 'srt' in subtitle_item and subtitle_item['srt']:
                    srt_content = subtitle_item['srt']
                    # SRT'yi parse et
                    plain_text = parse_srt_to_text(srt_content)

                    print(f"  📏 SRT uzunluğu: {len(srt_content)} karakter")
                    print(f"  📏 Düz metin uzunluğu: {len(plain_text)} karakter")
                    print()
                    print("  İlk 500 karakter:")
                    print(f"  {plain_text[:500]}...")
                else:
                    print("  ⚠️ SRT içeriği yok")
            else:
                print("  ⚠️ Subtitles listesi boş")
        else:
            print("  ❌ Altyazı bulunamadı")

        break

except Exception as e:
    print(f"❌ Hata: {str(e)}")
    import traceback
    print(traceback.format_exc())
