"""
Apify Subtitle Testi
Apify'ın altyazı çekme özelliğini test eder
"""

from apify_client import ApifyClient
from dotenv import load_dotenv
import os

load_dotenv()

client = ApifyClient(os.getenv('APIFY_API_KEY'))
video_url = "https://youtu.be/VtHvkBWToJs"

# Apify dokümantasyonuna göre doğru parametreler
run_input = {
    "startUrls": [{"url": video_url}],
    "downloadSubtitles": True,  # Altyazıları indir
    "saveSubtitlesToKVS": True,  # Key-Value Store'a kaydet
    "subtitleLang": "en",  # İngilizce altyazı
    "preferAutoGeneratedSubtitles": False,  # Manuel altyazıları tercih et
}

print("🧪 Apify actor test ediliyor...")
print(f"📺 Video: {video_url}")
print(f"⚙️ Parametreler: {run_input}")
print()

try:
    # Actor'ü çalıştır
    run = client.actor("streamers/youtube-scraper").call(run_input=run_input)

    print("✅ Actor çalıştırıldı")
    print(f"🆔 Run ID: {run.get('id')}")
    print()

    # Dataset sonuçlarını kontrol et
    print("📊 Dataset sonuçları:")
    for item in client.dataset(run["defaultDatasetId"]).iterate_items():
        print(f"  Video Başlığı: {item.get('title', 'N/A')}")
        print(f"  Subtitles (dataset): {item.get('subtitles', 'YOK')}")
        print()
        break

    # Key-Value Store'u kontrol et
    print("🔑 Key-Value Store kontrol ediliyor...")
    kvs_id = run.get("defaultKeyValueStoreId")
    if kvs_id:
        print(f"  KVS ID: {kvs_id}")
        # KVS'deki kayıtları listele
        kvs_client = client.key_value_store(kvs_id)
        # Genellikle altyazılar "subtitles" veya video ID ile kaydedilir
        print("  KVS içeriği kontrol ediliyor...")
    else:
        print("  ⚠️ KVS ID bulunamadı")

except Exception as e:
    print(f"❌ Hata: {str(e)}")
    import traceback
    print(traceback.format_exc())
